<Model> ::= Sequential([Dense(units = <unit_num>,activation='\"relu\"',input_shape = self.X.shape[1]), <hidden_layers>,Dense(units = self.n_classes, activation = '\"softmax\"')])
<hidden_layers> ::= <Dense> | <hidden_layers>, <Dense>
<Dense> ::= Dense(units = <DenseUnits>, activation = '\"relu\"')
<DenseUnits> ::= 16 | 32 | 64 | 128 | 256 | 512 

